#!/usr/bin/env bash
# SessionStart hook — injects in-flight wiki state at the top of every session
# so the coordination contract's "read AGENT-HANDOFF.md first" has mechanical
# backup instead of relying on the agent remembering.
set -uo pipefail
WIKI="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$WIKI" || exit 0

handoff_updated=$(sed -n 's/^updated: //p' AGENT-HANDOFF.md 2>/dev/null | head -1)
handoff_age_h="?"
[[ -f AGENT-HANDOFF.md ]] && handoff_age_h=$(( ($(date +%s) - $(stat -f %m AGENT-HANDOFF.md)) / 3600 ))

ingest_count=$(find ingest -path ingest/audio -prune -o -name "*.md" ! -name ".gitkeep" -print 2>/dev/null | wc -l | tr -d ' ')

inbox_pending=$(grep -c '^- ' .claude/inbox/wiki-question-inbox.md 2>/dev/null || true)
inbox_pending=${inbox_pending:-0}

lint_line=$(awk '/^## Last Structural Lint/,/^---$/' AGENT-HANDOFF.md 2>/dev/null \
  | grep -m1 '\*\*Result:' | sed 's/.*\*\*Result:\*\* //' | cut -c1-140)

scan_status="never run — bootstrap with: bash .claude/scripts/nightly-leak-scan.sh"
[[ -f .claude/logs/leak-scan-status ]] && scan_status=$(head -1 .claude/logs/leak-scan-status)

# Surface unresolved harness-health findings at the very top — this is the
# can't-miss surface for scheduled-job failures (the osascript banner the
# watchdog also fires is ephemeral and missed when the Mac is asleep/away).
harness_line=""
HS=".claude/logs/harness-status"
if [[ -f "$HS" ]] && [[ "$(awk -F'\t' 'NR==1{print $1}' "$HS")" == "needs-you" ]]; then
  h_since=$(awk -F'\t' 'NR==1{print $3}' "$HS")
  h_issues=$(awk 'NR>1' "$HS" | paste -sd'; ' - | cut -c1-220)
  # Staleness guard: the watchdog writes harness-status once daily (08:00), so a
  # leak-scan alert can outlive the problem (the 02:30 scan may have gone clean
  # since). If the alert is only about the leak gate and the CURRENT gate status
  # is clean + newer than the alert, say so instead of crying wolf.
  if [[ "$h_issues" == *"leak-scan-status is NOT clean"* ]] \
     && [[ -f .claude/logs/leak-scan-status ]] \
     && head -1 .claude/logs/leak-scan-status | grep -q '^clean' \
     && [[ .claude/logs/leak-scan-status -nt "$HS" ]]; then
    harness_line="- ℹ stale harness alert: leak gate has gone CLEAN since the last 08:00 watchdog run — alert self-clears at the next run. Other issues (if any): ${h_issues}"
  else
    harness_line="- ⚠ HARNESS ALERT (since ${h_since:-?}): ${h_issues} — see .claude/logs/harness-health.log"
  fi
fi

echo "[life-wiki session context — generated by .claude/hooks/session-start.sh]"
[[ -n "$harness_line" ]] && echo "$harness_line"
cat <<EOF
- AGENT-HANDOFF.md: updated ${handoff_updated:-unknown} (mtime ${handoff_age_h}h ago). Read it before working — hard rule.
- Last recorded structural lint: ${lint_line:-unknown — see AGENT-HANDOFF.md}
- Ingest queue: ${ingest_count} file(s) pending in ingest/
- Question inbox: ${inbox_pending} pending line(s) in .claude/inbox/wiki-question-inbox.md$( [[ "$inbox_pending" != "0" ]] && printf ' — run /inbox-triage' )
- Nightly leak scan: ${scan_status}
EOF
exit 0
