#!/usr/bin/env python3
"""backlink_timeline.py — deterministic backlink + timeline-spine builder.

WHY: journal/appointment entries link OUT to entity pages (providers/conditions/
medications/biomarkers) but entities don't link BACK, so most dated entries are
traversal orphans — unreachable by Bernard (who walks in-file [[wikilinks]], not
GBrain). This injects reciprocal body backlinks into each entity page and builds
a master chronological timeline page, both as plain markdown so they reach the
mirror.

Design guarantees:
- Writes only managed regions delimited by sentinels; never disturbs hand-authored
  content. Fully idempotent: rerunning produces a byte-identical file.
- Backlink sections are appended at end of file (the two-zone append-only zone),
  never inside the compiled-truth zone above the second '---'.
- Only links to entity files that actually exist (no phantom [[REDACTED]]-style nodes).
- Never reads or writes raw/ or ingest/.
- --apply writes; default is dry-run (reports what would change, exit 0).

Exit codes: 0 ok (incl. dry-run). 2 = bad invocation.
"""
import argparse, os, re, sys, glob

ENTITY_CATS = ["conditions", "medications", "biomarkers", "providers"]
START = "<!-- AUTO-MENTIONED-IN:START (generated by build-backlinks.sh — do not hand-edit) -->"
END = "<!-- AUTO-MENTIONED-IN:END -->"
TL_START = "<!-- AUTO-TIMELINE:START (generated by build-backlinks.sh — do not hand-edit) -->"
TL_END = "<!-- AUTO-TIMELINE:END -->"

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")
LINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


def split_frontmatter(text):
    """Return (frontmatter_str, body_str). Empty fm if none."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            nl = text.find("\n", end + 1)
            return text[3:end], text[nl + 1:] if nl != -1 else ""
    return "", text


def parse_list_field(fm, field):
    """Parse a YAML list field, both inline [a, b] and block (- a) forms."""
    vals = []
    # inline: field: [a, b, c]
    m = re.search(rf"^{field}:\s*\[(.*?)\]\s*$", fm, re.MULTILINE)
    if m:
        for part in m.group(1).split(","):
            p = part.strip().strip("'\"")
            if p:
                vals.append(p)
        return vals
    # block form
    m = re.search(rf"^{field}:\s*$", fm, re.MULTILINE)
    if m:
        rest = fm[m.end():]
        for line in rest.splitlines():
            if re.match(r"^\s*-\s+", line):
                vals.append(re.sub(r"^\s*-\s+", "", line).strip().strip("'\""))
            elif line.strip() and not line.startswith(" "):
                break
    return vals


def entry_date(path, fm):
    m = DATE_RE.search(os.path.basename(path))
    if m:
        return m.group(1)
    m = re.search(r"^date(?:_created)?:\s*(\d{4}-\d{2}-\d{2})", fm, re.MULTILINE)
    return m.group(1) if m else None


def entry_title(fm, path):
    m = re.search(r"^title:\s*(.+)$", fm, re.MULTILINE)
    if m:
        return m.group(1).strip().strip("'\"")
    return os.path.basename(path)[:-3]


def replace_managed(text, start, end, block):
    """Insert/replace/remove a sentinel-delimited block. block=None removes it."""
    si = text.find(start)
    if block is None:
        # remove existing managed region (and trailing blank padding) if present
        if si != -1:
            ei = text.find(end, si)
            if ei != -1:
                ei += len(end)
                cleaned = text[:si].rstrip("\n") + ("\n" if text[:si].strip() else "") + text[ei:].lstrip("\n")
                return cleaned.rstrip("\n") + "\n"
        return text
    new_region = f"{start}\n{block}\n{end}"
    if si != -1:
        ei = text.find(end, si)
        if ei != -1:
            ei += len(end)
            return text[:si] + new_region + text[ei:]
    # append at end (append-only zone), ensuring spacing
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + new_region + "\n"


def build(wiki_root, apply, timeline_out):
    shared = os.path.join(wiki_root, "wikis/health/shared")
    entries_dir = os.path.join(wiki_root, "wikis/journal/wiki/entries")

    # map of existing entity key -> abs path
    entity_key = {}  # "wikis/health/shared/conditions/eds" -> path
    for cat in ENTITY_CATS:
        for f in glob.glob(os.path.join(shared, cat, "*.md")):
            key = "wikis/health/shared/%s/%s" % (cat, os.path.basename(f)[:-3])
            entity_key[key] = f

    # gather entry -> referenced entities
    mentions = {k: [] for k in entity_key}  # entity_key -> list of (date, entrykey, title)
    timeline = []  # (date, entrykey, title, [entity_keys])
    entries = sorted(glob.glob(os.path.join(entries_dir, "*.md")))
    for ef in entries:
        txt = open(ef, encoding="utf-8", errors="ignore").read()
        fm, body = split_frontmatter(txt)
        date = entry_date(ef, fm)
        title = entry_title(fm, ef)
        ekey = "wikis/journal/wiki/entries/%s" % (os.path.basename(ef)[:-3])
        refs = set()
        # frontmatter slugs
        for cat, field in [("conditions", "conditions"), ("medications", "medications"),
                           ("providers", "providers")]:
            for slug in parse_list_field(fm, field):
                k = "wikis/health/shared/%s/%s" % (cat, slug)
                if k in entity_key:
                    refs.add(k)
        # body links
        for m in LINK_RE.finditer(body):
            tgt = m.group(1).split("|")[0].split("#")[0].strip().lstrip("./")
            if tgt.endswith(".md"):
                tgt = tgt[:-3]
            if tgt in entity_key:
                refs.add(tgt)
        for k in refs:
            mentions[k].append((date or "0000-00-00", ekey, title))
        timeline.append((date or "0000-00-00", ekey, title, sorted(refs)))

    # write entity backlink sections
    changed = []
    for k, path in sorted(entity_key.items()):
        ms = sorted(mentions[k], key=lambda x: x[0], reverse=True)
        if ms:
            lines = ["## Mentioned In", "",
                     "_Dated entries that reference this page (auto-maintained for graph traversal)._", ""]
            for date, ekey, title in ms:
                d = date if date != "0000-00-00" else "undated"
                lines.append(f"- {d} — [[{ekey}]]")
            block = "\n".join(lines)
        else:
            block = None  # no mentions: remove any stale section, add nothing
        old = open(path, encoding="utf-8", errors="ignore").read()
        new = replace_managed(old, START, END, block)
        if new != old:
            changed.append(path)
            if apply:
                open(path, "w", encoding="utf-8").write(new)

    # build timeline page
    tl = sorted([t for t in timeline if t[0] != "0000-00-00"], key=lambda x: x[0])
    undated = [t for t in timeline if t[0] == "0000-00-00"]
    body_lines = ["_Every dated journal/appointment entry, chronological. Auto-maintained — "
                  "the traversal spine that lets agents reconstruct timelines._", ""]
    cur_year = None
    for date, ekey, title, refs in tl:
        yr = date[:4]
        if yr != cur_year:
            cur_year = yr
            body_lines += ["", f"### {yr}", ""]
        ent = ("  ·  " + ", ".join(f"[[{r}]]" for r in refs)) if refs else ""
        body_lines.append(f"- **{date}** — [[{ekey}]]{ent}")
    if undated:
        body_lines += ["", "### Undated", ""]
        for date, ekey, title, refs in undated:
            body_lines.append(f"- [[{ekey}]]")
    tl_block = "\n".join(body_lines)

    if timeline_out:
        if os.path.exists(timeline_out):
            old = open(timeline_out, encoding="utf-8", errors="ignore").read()
        else:
            old = ("---\ntype: overview\nstatus: active\ndomain: health\n"
                   "date_created: auto\ndate_updated: auto\nsource_paths: []\n"
                   "confidence: high\ntags: [timeline, index]\n---\n\n"
                   "# Master Timeline\n\n" + TL_START + "\n" + TL_END + "\n")
        new = replace_managed(old, TL_START, TL_END, tl_block)
        if new != old:
            changed.append(timeline_out)
            if apply:
                os.makedirs(os.path.dirname(timeline_out), exist_ok=True)
                open(timeline_out, "w", encoding="utf-8").write(new)

    return changed, len([k for k in mentions if mentions[k]]), len(tl)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--wiki-root", required=True)
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--timeline-out", default="")
    a = ap.parse_args()
    if not os.path.isdir(a.wiki_root):
        print("bad --wiki-root", file=sys.stderr)
        return 2
    changed, ent_with, n_tl = build(a.wiki_root, a.apply, a.timeline_out or None)
    mode = "APPLIED" if a.apply else "DRY-RUN"
    print(f"[backlink_timeline {mode}] entity pages with mentions: {ent_with}; "
          f"timeline entries: {n_tl}; files {'changed' if a.apply else 'would change'}: {len(changed)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
