#!/usr/bin/env python3
"""daily_score.py — deterministic Bearable-style daily symptom score from Guava CSV exports.

Methodology (curator-approved 2026-07-02):
  - Per (day, symptom): the day's WORST reading (max of up to 4 logs).
  - Daily burden = sum(v^2 / 10) over symptoms logged that day (severe symptoms dominate).
  - Score = midrank percentile (0-100, rounded) of the day's burden within the trailing
    365 days of valid days (including the day itself). HIGHER = WORSE.
    Requires >= 28 valid days of history in the window, else burden only (score blank).
  - A day is valid if it has >= 5 symptom entries; missing days are never interpolated.
  - Energy/Mood reported alongside on their raw scales, not folded into the burden.

Outputs (only between sentinel markers / to the scores CSV — hand-written zones untouched):
  - Managed summary block + managed data block in daily-symptom-score.md
  - daily-symptom-scores.csv (full history, machine-readable, for ad-hoc charting)

Idempotent: the sentinel META line records source CSV basename + row count; if unchanged
and outputs exist, exits with "changed: 0". Purely mechanical; no model, no network.
"""

import argparse
import csv
import glob
import os
import re
import sys
from collections import defaultdict
from datetime import date, timedelta

SENT_START = "<!-- AUTO-DAILY-SCORE:START (generated by build-daily-score.sh — do not hand-edit) -->"
SENT_END = "<!-- AUTO-DAILY-SCORE:END -->"
SUM_START = "<!-- AUTO-SCORE-SUMMARY:START (generated by build-daily-score.sh — do not hand-edit) -->"
SUM_END = "<!-- AUTO-SCORE-SUMMARY:END -->"
META_RE = re.compile(r"<!-- AUTO-DAILY-SCORE:META source=(\S+) rows=(\d+) -->")

WINDOW_DAYS = 365
MIN_HISTORY = 28
MIN_ENTRIES = 5
TREND_THRESHOLD = 5.0  # score points; below this a 7d-vs-30d delta is "stable"

DOMAINS = {
    "Pain": ["Generalised pain", "Abdominal pain", "Migraine pain"],
    "GI": ["Nausea", "Constipation"],
    "Breathing": ["Shortness of breath"],
    "Cognition": ["Brain fog"],
}

SCORES_CSV_COLUMNS = [
    "date", "burden", "score", "n_symptoms", "n_entries",
    "energy", "mood", "top_drivers", "flags",
]


def find_latest_csv(wiki_root):
    pattern = os.path.join(
        wiki_root, "wikis/health/personal-tracking/raw/*guava-health-symptom-tracking.csv")
    candidates = sorted(glob.glob(pattern))
    if not candidates:
        return None
    # Filenames carry YYYY-MM-DD-YYYY-MM-DD prefixes; the latest end date sorts last.
    return candidates[-1]


def parse_date(s):
    s = (s or "").strip()[:10]
    try:
        y, m, d = s.split("-")
        return date(int(y), int(m), int(d))
    except (ValueError, AttributeError):
        return None


def load_rows(csv_path):
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def clamp(v, lo, hi, warnings, label):
    if v < lo or v > hi:
        warnings.append("%s value %s clamped to [%s,%s]" % (label, v, lo, hi))
        return max(lo, min(hi, v))
    return v


def compute_days(rows):
    """Return (days dict keyed by date, warnings list).

    days[d] = {symptoms: {name: day-max}, n_entries, energy, mood}
    """
    warnings = []
    sym = defaultdict(dict)     # date -> {name: max value}
    entries = defaultdict(int)  # date -> raw symptom-row count
    energy = defaultdict(list)
    mood = defaultdict(list)

    for r in rows:
        rtype = (r.get("type") or "").strip()
        d = parse_date(r.get("datetime"))
        if d is None:
            continue
        val = (r.get("value") or "").strip()
        if rtype == "Symptoms":
            name = re.sub(r"\s+", " ", (r.get("name") or "").strip())
            if not name or not val:
                continue
            try:
                v = float(val)
            except ValueError:
                continue
            v = clamp(v, 0.0, 10.0, warnings, "%s %s" % (d, name))
            entries[d] += 1
            if name not in sym[d] or v > sym[d][name]:
                sym[d][name] = v
        elif rtype in ("Energy", "Mood"):
            if not val:
                continue
            try:
                v = float(val)
            except ValueError:
                continue
            v = clamp(v, 1.0, 5.0, warnings, "%s %s" % (d, rtype))
            (energy if rtype == "Energy" else mood)[d].append(v)

    days = {}
    for d, symptoms in sym.items():
        days[d] = {
            "symptoms": symptoms,
            "n_entries": entries[d],
            "energy": max(energy[d]) if d in energy else None,
            "mood": max(mood[d]) if d in mood else None,
        }
    return days, warnings


def burden_of(symptoms):
    return sum(v * v / 10.0 for v in symptoms.values())


def top_drivers(symptoms, n=3):
    ranked = sorted(symptoms.items(), key=lambda kv: (-kv[1] * kv[1], kv[0]))
    return ["%s %g" % (name, v) for name, v in ranked[:n]]


def compute_scores(days):
    """Midrank percentile of each valid day's burden vs the trailing 365 valid days."""
    valid = sorted(d for d, info in days.items() if info["n_entries"] >= MIN_ENTRIES)
    burdens = {d: burden_of(days[d]["symptoms"]) for d in valid}
    scores = {}
    for d in valid:
        lo = d - timedelta(days=WINDOW_DAYS - 1)
        window = [burdens[x] for x in valid if lo <= x <= d]
        if len(window) < MIN_HISTORY:
            scores[d] = None
            continue
        b = burdens[d]
        less = sum(1 for x in window if x < b)
        equal = sum(1 for x in window if x == b)
        scores[d] = round((less + 0.5 * equal) / len(window) * 100)
    return valid, burdens, scores


def mean(xs):
    xs = [x for x in xs if x is not None]
    return sum(xs) / len(xs) if xs else None


def fmt(x, nd=1):
    return ("%%.%df" % nd) % x if x is not None else "—"


def direction(delta):
    if delta is None:
        return "no comparison"
    if delta <= -TREND_THRESHOLD:
        return "improving"
    if delta >= TREND_THRESHOLD:
        return "worsening"
    return "stable"


def window_mean(valid, values, latest, days_back):
    lo = latest - timedelta(days=days_back - 1)
    return mean([values[d] for d in valid if lo <= d <= latest])


def domain_day_mean(info, members):
    vals = [info["symptoms"][s] for s in members if s in info["symptoms"]]
    return mean(vals)


def build_report(days, valid, burdens, scores):
    """Compute every derived stat once; renderers below format it."""
    latest = valid[-1]
    r = {"latest": latest}
    r["latest_burden"] = burdens[latest]
    r["latest_score"] = scores[latest]
    r["latest_drivers"] = top_drivers(days[latest]["symptoms"])
    r["mean7"] = window_mean(valid, scores, latest, 7)
    r["mean30"] = window_mean(valid, scores, latest, 30)
    prior7_days = [d for d in valid
                   if latest - timedelta(days=13) <= d <= latest - timedelta(days=7)]
    r["prior7"] = mean([scores[d] for d in prior7_days])
    r["delta_7v30"] = (r["mean7"] - r["mean30"]) if (r["mean7"] is not None
                                                     and r["mean30"] is not None) else None
    r["direction"] = direction(r["delta_7v30"])

    # 35-day daily table rows (calendar days; gaps shown, never filled)
    table = []
    for i in range(34, -1, -1):
        d = latest - timedelta(days=i)
        if d in days and d in burdens:
            info = days[d]
            table.append({
                "date": d, "burden": burdens[d], "score": scores.get(d),
                "drivers": top_drivers(info["symptoms"]),
                "energy": info["energy"], "mood": info["mood"],
                "partial": info["n_entries"] < MIN_ENTRIES,
            })
        elif d in days:  # logged but below entry threshold
            table.append({"date": d, "burden": None, "score": None, "drivers": [],
                          "energy": days[d]["energy"], "mood": days[d]["mood"],
                          "partial": True})
        else:
            table.append({"date": d, "burden": None, "score": None, "drivers": [],
                          "energy": None, "mood": None, "partial": False})
    r["table"] = table

    # Per-domain trends: last 30 calendar days vs the 30 before
    dom = {}
    for label, members in sorted(DOMAINS.items()):
        cur = mean([domain_day_mean(days[d], members)
                    for d in valid if latest - timedelta(days=29) <= d <= latest])
        prev = mean([domain_day_mean(days[d], members)
                     for d in valid
                     if latest - timedelta(days=59) <= d <= latest - timedelta(days=30)])
        dom[label] = (cur, prev)
    for label, key in (("Energy (1–5, higher = better)", "energy"),
                       ("Mood (1–5, higher = better)", "mood")):
        cur = mean([days[d][key] for d in valid
                    if latest - timedelta(days=29) <= d <= latest])
        prev = mean([days[d][key] for d in valid
                     if latest - timedelta(days=59) <= d <= latest - timedelta(days=30)])
        dom[label] = (cur, prev)
    r["domains"] = dom

    # Biggest 7-day movers (symptom day-max means, last 7 valid-window vs prior 7)
    movers = []
    names = set()
    for d in valid:
        if latest - timedelta(days=13) <= d <= latest:
            names.update(days[d]["symptoms"])
    for name in sorted(names):
        cur = mean([days[d]["symptoms"].get(name) for d in valid
                    if latest - timedelta(days=6) <= d <= latest])
        prev = mean([days[d]["symptoms"].get(name) for d in valid
                     if latest - timedelta(days=13) <= d <= latest - timedelta(days=7)])
        if cur is not None and prev is not None and abs(cur - prev) >= 1.0:
            movers.append((name, prev, cur))
    movers.sort(key=lambda t: -abs(t[2] - t[1]))
    r["movers"] = movers[:5]

    # 12-month table
    months = []
    seen = []
    for d in valid:
        ym = (d.year, d.month)
        if ym not in seen:
            seen.append(ym)
    for ym in seen[-12:]:
        mdays = [d for d in valid if (d.year, d.month) == ym]
        mscores = [scores[d] for d in mdays if scores[d] is not None]
        months.append({
            "label": date(ym[0], ym[1], 1).strftime("%b %Y"),
            "n": len(mdays),
            "burden": mean([burdens[d] for d in mdays]),
            "score": mean(mscores),
            "best": min(mscores) if mscores else None,
            "worst": max(mscores) if mscores else None,
        })
    r["months"] = months
    return r


def render_summary(r):
    lines = [SUM_START]
    score_txt = ("%d / 100" % r["latest_score"]) if r["latest_score"] is not None \
        else "(building baseline — burden %s)" % fmt(r["latest_burden"])
    lines.append("**Latest daily symptom score: %s** (%s — higher = worse; "
                 "vs her own past year)." % (score_txt, r["latest"].isoformat()))
    lines.append("")
    lines.append("- 7-day mean **%s** vs 30-day mean **%s** → **%s**"
                 % (fmt(r["mean7"], 0), fmt(r["mean30"], 0), r["direction"]))
    lines.append("- Top drivers on %s: %s"
                 % (r["latest"].isoformat(), ", ".join(r["latest_drivers"]) or "—"))
    lines.append("- **Data through %s** (manual Guava export — may lag today's date)."
                 % r["latest"].isoformat())
    lines.append(SUM_END)
    return "\n".join(lines)


def render_block(r, source_name, source_rows):
    L = [SENT_START,
         "<!-- AUTO-DAILY-SCORE:META source=%s rows=%d -->" % (source_name, source_rows),
         ""]
    L.append("### Daily scores — last 35 days")
    L.append("")
    L.append("Score 0–100, **higher = worse**, percentile vs her trailing 365 days. "
             "`—` = not logged that day (never interpolated).")
    L.append("")
    L.append("| Date | Score | Burden | Top drivers | Energy | Mood |")
    L.append("|---|---|---|---|---|---|")
    for row in r["table"]:
        flag = " *(partial)*" if row["partial"] and row["burden"] is not None else ""
        L.append("| %s | %s%s | %s | %s | %s | %s |" % (
            row["date"].isoformat(),
            fmt(row["score"], 0), flag,
            fmt(row["burden"]),
            ", ".join(row["drivers"]) or "—",
            fmt(row["energy"], 0), fmt(row["mood"], 0)))
    L.append("")
    L.append("### Per-domain trends — last 30 days vs the 30 before")
    L.append("")
    L.append("| Domain | Prior 30d | Last 30d | Change |")
    L.append("|---|---|---|---|")
    for label, (cur, prev) in r["domains"].items():
        if cur is not None and prev is not None:
            arrow = "↑" if cur > prev + 0.2 else ("↓" if cur < prev - 0.2 else "→")
            change = "%s %+.1f" % (arrow, cur - prev)
        else:
            change = "—"
        L.append("| %s | %s | %s | %s |" % (label, fmt(prev), fmt(cur), change))
    L.append("")
    L.append("### Biggest 7-day movers (symptom day-max, mean)")
    L.append("")
    if r["movers"]:
        for name, prev, cur in r["movers"]:
            word = "worsened" if cur > prev else "improved"
            L.append("- **%s** %s: %.1f → %.1f" % (name, word, prev, cur))
    else:
        L.append("- No symptom moved by ≥1 point week-over-week.")
    L.append("")
    L.append("### Monthly trend — last 12 months")
    L.append("")
    L.append("| Month | Days logged | Mean burden | Mean score | Best day | Worst day |")
    L.append("|---|---|---|---|---|---|")
    for m in r["months"]:
        L.append("| %s | %d | %s | %s | %s | %s |" % (
            m["label"], m["n"], fmt(m["burden"]), fmt(m["score"], 0),
            fmt(m["best"], 0), fmt(m["worst"], 0)))
    L.append("")
    L.append("### Charts")
    L.append("")
    L.append("![Daily score, last 30 days](charts/score-30d.png)")
    L.append("")
    L.append("![Monthly trend, last 12 months](charts/score-12m.png)")
    L.append("")
    L.append(SENT_END)
    return "\n".join(L)


def replace_between(text, start, end, replacement, label):
    i, j = text.find(start), text.find(end)
    if i == -1 or j == -1 or j < i:
        raise SystemExit("ERROR: %s sentinels missing/malformed in target page" % label)
    return text[:i] + replacement + text[j + len(end):]


def bump_date_last_updated(text, today_str):
    return re.sub(r"^date_last_updated: .*$",
                  "date_last_updated: %s" % today_str, text, count=1, flags=re.M)


def scores_csv_text(days, valid, burdens, scores):
    out = [",".join(SCORES_CSV_COLUMNS)]
    all_days = sorted(days)
    w = csv.writer(_ListWriter(out))
    for d in all_days:
        info = days[d]
        is_valid = info["n_entries"] >= MIN_ENTRIES
        flags = "" if is_valid else "partial"
        w.writerow([
            d.isoformat(),
            "%.1f" % burdens[d] if d in burdens else "",
            scores.get(d, None) if scores.get(d) is not None else "",
            len(info["symptoms"]),
            info["n_entries"],
            "%g" % info["energy"] if info["energy"] is not None else "",
            "%g" % info["mood"] if info["mood"] is not None else "",
            "; ".join(top_drivers(info["symptoms"])),
            flags,
        ])
    return "\n".join(out) + "\n"


class _ListWriter(object):
    def __init__(self, lines):
        self.lines = lines

    def write(self, s):
        s = s.rstrip("\r\n")
        if s:
            self.lines.append(s)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--wiki-root", required=True)
    ap.add_argument("--csv", help="Guava export CSV (default: latest in personal-tracking/raw/)")
    ap.add_argument("--out", help="score page (default: personal-tracking/wiki/daily-symptom-score.md)")
    ap.add_argument("--scores-csv", help="machine-readable output (default: alongside page)")
    ap.add_argument("--apply", action="store_true", help="write outputs (default: dry-run)")
    args = ap.parse_args()

    root = args.wiki_root
    csv_path = args.csv or find_latest_csv(root)
    if not csv_path or not os.path.exists(csv_path):
        print("ERROR: no Guava symptom-tracking CSV found")
        return 1
    page_path = args.out or os.path.join(
        root, "wikis/health/personal-tracking/wiki/daily-symptom-score.md")
    scores_path = args.scores_csv or os.path.join(
        os.path.dirname(page_path), "daily-symptom-scores.csv")

    rows = load_rows(csv_path)
    source_name, source_rows = os.path.basename(csv_path), len(rows)

    if not os.path.exists(page_path):
        print("ERROR: %s does not exist — author the page (with sentinels) first" % page_path)
        return 1
    page = open(page_path, encoding="utf-8").read()

    m = META_RE.search(page)
    if (m and m.group(1) == source_name and int(m.group(2)) == source_rows
            and os.path.exists(scores_path)):
        print("daily-score: changed: 0 (source %s unchanged, %d rows)"
              % (source_name, source_rows))
        return 0

    days, warnings = compute_days(rows)
    for w in warnings[:20]:
        print("warn: %s" % w)
    if len(warnings) > 20:
        print("warn: (%d further clamp warnings suppressed)" % (len(warnings) - 20))

    valid, burdens, scores = compute_scores(days)
    if not valid:
        print("daily-score: no valid days (need >= %d symptom entries/day) — nothing to write"
              % MIN_ENTRIES)
        return 0

    report = build_report(days, valid, burdens, scores)
    new_page = replace_between(page, SUM_START, SUM_END, render_summary(report), "summary")
    new_page = replace_between(new_page, SENT_START, SENT_END,
                               render_block(report, source_name, source_rows), "data")
    new_page = bump_date_last_updated(new_page, report["latest"].isoformat())
    csv_text = scores_csv_text(days, valid, burdens, scores)

    summary = ("daily-score APPLIED days=%d latest=%s score=%s direction=%s source=%s"
               % (len(valid), report["latest"].isoformat(),
                  report["latest_score"] if report["latest_score"] is not None else "n/a",
                  report["direction"], source_name))

    if args.apply:
        with open(page_path, "w", encoding="utf-8") as f:
            f.write(new_page)
        with open(scores_path, "w", encoding="utf-8") as f:
            f.write(csv_text)
        print(summary)
    else:
        print("[dry-run] would write %s and %s" % (page_path, scores_path))
        print("[dry-run] " + summary)
        print("[dry-run] summary block would be:\n" + render_summary(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
