#!/usr/bin/env python3
"""hypothesis_register.py — recommendation ③: working-hypotheses register.

Harvests inline reasoning markers the wiki already uses per CLAUDE.md —
  > Hypothesis: ...        (uncited inference)
  Needs verification: ...  (claim awaiting a source)
  > Contradiction: ...     (preserved conflicting claims)
— into one reviewable page with a backlink to each source. Lifecycle: the marker
lives inline (source of truth); this page is a generated index; once the curator
cites/resolves it on the source page, it drops off here on the next run.

Compiled-truth pages only — raw/ and ingest/ are excluded so source-document
quotes don't pollute the register. Idempotent (sentinel-delimited managed block).
"""
import argparse, os, re, glob, sys

START = "<!-- AUTO-HYPOTHESES:START (generated by build-hypothesis-register.sh — do not hand-edit) -->"
END = "<!-- AUTO-HYPOTHESES:END -->"
KINDS = [("Hypothesis", re.compile(r"^>?\s*Hypothesis:\s*(.*)$")),
         ("Needs verification", re.compile(r"^>?\s*Needs verification:\s*(.*)$")),
         ("Contradiction", re.compile(r"^>?\s*Contradiction:\s*(.*)$"))]
HDR = {"Hypothesis": "Hypotheses", "Needs verification": "Needs Verification",
       "Contradiction": "Contradictions"}


def page_key(path, wiki_root):
    rel = os.path.relpath(path, wiki_root)
    return rel[:-3] if rel.endswith(".md") else rel


def split_fm(text):
    if text.startswith("---"):
        e = text.find("\n---", 3)
        if e != -1:
            nl = text.find("\n", e + 1)
            return (text[nl + 1:] if nl != -1 else ""), (text[:nl + 1] if nl != -1 else text)
    return text, ""


def harvest(wiki_root):
    found = {k: [] for k, _ in KINDS}  # kind -> [(page_key, text)]
    skip = ("/raw/", "/ingest/")
    for path in glob.glob(os.path.join(wiki_root, "wikis/**/*.md"), recursive=True):
        if any(s in path for s in skip):
            continue
        key = page_key(path, wiki_root)
        if key.endswith("working-hypotheses"):  # never harvest the register itself
            continue
        body, _ = split_fm(open(path, encoding="utf-8", errors="ignore").read())
        lines = body.splitlines()
        i = 0
        while i < len(lines):
            line = lines[i]
            matched = False
            for kind, rx in KINDS:
                m = rx.match(line.strip())
                if m:
                    text = m.group(1).strip()
                    # absorb blockquote continuation lines
                    j = i + 1
                    while j < len(lines) and lines[j].strip().startswith(">") and \
                            not any(r.match(lines[j].strip()) for _, r in KINDS):
                        cont = lines[j].strip().lstrip(">").strip()
                        if cont:
                            text += " " + cont
                        j += 1
                    if text:
                        found[kind].append((key, " ".join(text.split())))
                    i = j
                    matched = True
                    break
            if not matched:
                i += 1
    return found


def render(found):
    out = []
    for kind, _ in KINDS:
        items = found[kind]
        out.append(f"## {HDR[kind]} ({len(items)})")
        out.append("")
        if not items:
            out.append("_None._")
        else:
            for key, text in sorted(items):
                short = text if len(text) <= 400 else text[:397] + "…"
                out.append(f"- **[[{key}]]** — {short}")
        out.append("")
    return "\n".join(out).rstrip()


def replace_managed(text, block):
    region = f"{START}\n{block}\n{END}"
    si = text.find(START)
    if si != -1:
        ei = text.find(END, si)
        if ei != -1:
            return text[:si] + region + text[ei + len(END):]
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + region + "\n"


def build(wiki_root, out_path, apply):
    found = harvest(wiki_root)
    block = render(found)
    if os.path.exists(out_path):
        old = open(out_path, encoding="utf-8", errors="ignore").read()
    else:
        old = ("---\ntype: overview\nstatus: active\ndomain: health\n"
               "date_created: auto\ndate_updated: auto\nsource_paths: []\n"
               "confidence: high\ntags: [hypotheses, register, index]\n---\n\n"
               "# Working Hypotheses Register\n\n"
               "_Auto-compiled from inline `> Hypothesis:` / `Needs verification:` / "
               "`> Contradiction:` markers across the wiki. Resolve one by citing it on "
               "its source page — it drops off here next run._\n\n" + START + "\n" + END + "\n")
    new = replace_managed(old, block)
    changed = new != old
    if changed and apply:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        open(out_path, "w", encoding="utf-8").write(new)
    counts = {k: len(v) for k, v in found.items()}
    return changed, counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--wiki-root", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    if not os.path.isdir(a.wiki_root):
        print("bad --wiki-root", file=sys.stderr)
        return 2
    changed, counts = build(a.wiki_root, a.out, a.apply)
    mode = "APPLIED" if a.apply else "DRY-RUN"
    print(f"[hypothesis_register {mode}] Hypothesis={counts['Hypothesis']} "
          f"NeedsVerification={counts['Needs verification']} Contradiction={counts['Contradiction']}; "
          f"{'changed' if changed else 'no change'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
