#!/usr/bin/env python3
"""Edge-case tests for daily_score.py."""
import csv
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import date, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.join(HERE, "daily_score.py")
fails = []

# Sentinel constants copied verbatim from daily_score.py — must match exactly
# so fixture pages are recognized by the module's replace_between().
SUM_START = "<!-- AUTO-SCORE-SUMMARY:START (generated by build-daily-score.sh — do not hand-edit) -->"
SUM_END = "<!-- AUTO-SCORE-SUMMARY:END -->"
SENT_START = "<!-- AUTO-DAILY-SCORE:START (generated by build-daily-score.sh — do not hand-edit) -->"
SENT_END = "<!-- AUTO-DAILY-SCORE:END -->"

CSV_HEADER = ["type", "datetime", "datetime_end", "name", "value", "unit",
              "tags", "data", "notes", "added"]


def w(p, c):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", encoding="utf-8").write(c)


def check(name, cond, detail=""):
    print(("PASS" if cond else "FAIL"), "-", name, ("" if cond else f":: {detail}"))
    if not cond:
        fails.append(name)


def sym_row(dt, name, value, notes=""):
    return ["Symptoms", dt, "", name, value, "", "", "", notes, dt + "T00:00:00"]


def energy_row(dt, value):
    return ["Energy", dt, "", "", value, "", "", "", "", dt + "T00:00:00"]


def mood_row(dt, value):
    return ["Mood", dt, "", "", value, "", "", "", "", dt + "T00:00:00"]


def write_csv(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        cw = csv.writer(f)
        cw.writerow(CSV_HEADER)
        for r in rows:
            cw.writerow(r)


def read_scores_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def page_text(dlu="2020-01-01", include_data_sentinels=True):
    parts = [
        "---\n",
        "type: overview\n",
        "domain: health\n",
        "date_last_updated: %s\n" % dlu,
        "---\n\n",
        "# Daily Symptom Score\n\n",
        "HANDWRITTEN-INTRO-MARKER must survive edits untouched.\n\n",
        SUM_START + "\nplaceholder-summary-content\n" + SUM_END + "\n\n",
        "HANDWRITTEN-MIDDLE-MARKER must also survive.\n\n",
    ]
    if include_data_sentinels:
        parts.append(SENT_START + "\nplaceholder-data-content\n" + SENT_END + "\n\n")
    parts.append("HANDWRITTEN-TAIL-MARKER final text.\n")
    return "".join(parts)


def run(root, csv_path, out_path, scores_path, apply):
    args = [sys.executable, MOD, "--wiki-root", root, "--csv", csv_path,
            "--out", out_path, "--scores-csv", scores_path]
    if apply:
        args.append("--apply")
    return subprocess.run(args, capture_output=True, text=True)


def main():
    root = tempfile.mkdtemp()
    try:
        # ---------- Scenario A: day-max aggregation, burden formula, partial-day boundary ----------
        a_csv = f"{root}/a/guava.csv"
        a_out = f"{root}/a/page.md"
        a_scores = f"{root}/a/scores.csv"
        write_csv(a_csv, [
            # day 2026-01-05: Nausea logged 3x (4, 9, 2) -> day-max 9; AbdominalPain once (2)
            # burden = 9^2/10 + 2^2/10 + 0 + 0 = 8.1 + 0.4 = 8.5  (contract's worked example)
            sym_row("2026-01-05", "Nausea", 4),
            sym_row("2026-01-05", "Nausea", 9),
            sym_row("2026-01-05", "Nausea", 2),
            sym_row("2026-01-05", "AbdominalPain", 2),
            sym_row("2026-01-05", "Filler", 0),
            sym_row("2026-01-05", "Filler2", 0),
            energy_row("2026-01-05", 3),
            energy_row("2026-01-05", 4),  # day-max energy = 4
            mood_row("2026-01-05", 2),
            # day 2026-01-06: only 4 symptom entries -> partial (below MIN_ENTRIES=5)
            sym_row("2026-01-06", "Nausea", 5),
            sym_row("2026-01-06", "Filler", 0),
            sym_row("2026-01-06", "Filler2", 0),
            sym_row("2026-01-06", "Filler3", 0),
        ])
        w(a_out, page_text())
        r = run(root, a_csv, a_out, a_scores, True)
        check("scenario A: apply exits 0", r.returncode == 0, r.stderr)
        by_date = {row["date"]: row for row in read_scores_csv(a_scores)}
        d1, d2 = by_date["2026-01-05"], by_date["2026-01-06"]
        check("day-max: burden uses max of dup Nausea rows (9, not 4 or 2)",
              d1["burden"] == "8.5", d1)
        check("day-max: top_drivers reflects max value 9, not 4/2",
              "Nausea 9" in d1["top_drivers"], d1["top_drivers"])
        check("energy day-max reported (4, not 3)", d1["energy"] == "4", d1)
        check("mood reported (2)", d1["mood"] == "2", d1)
        check("day1 n_entries=6, valid (flags empty)",
              d1["n_entries"] == "6" and d1["flags"] == "", d1)
        check("day2 (4 entries) flagged partial", d2["flags"] == "partial", d2)
        check("day2 burden empty (below MIN_ENTRIES, excluded from ranking)",
              d2["burden"] == "", d2)
        check("day2 score empty", d2["score"] == "", d2)
        check("day2 n_entries=4 recorded even though partial", d2["n_entries"] == "4", d2)

        # ---------- Scenario B: midrank percentile, ties, min-history threshold ----------
        b_csv = f"{root}/b/guava.csv"
        b_out = f"{root}/b/page.md"
        b_scores = f"{root}/b/scores.csv"
        START = date(2025, 1, 1)
        b_rows = []
        # days 0..36: distinct strictly-increasing Target values 0, 0.25, ..., 9.0 (37 days)
        for i in range(37):
            d = (START + timedelta(days=i)).isoformat()
            b_rows.append(sym_row(d, "Target", i * 0.25))
            for j in range(1, 5):
                b_rows.append(sym_row(d, "Filler%d" % j, 1.0))
        # days 37..39: 3-way tie at 9.5, strictly above every prior day's value
        for i in range(37, 40):
            d = (START + timedelta(days=i)).isoformat()
            b_rows.append(sym_row(d, "Target", 9.5))
            for j in range(1, 5):
                b_rows.append(sym_row(d, "Filler%d" % j, 1.0))
        write_csv(b_csv, b_rows)
        w(b_out, page_text())
        r = run(root, b_csv, b_out, b_scores, True)
        check("scenario B: apply exits 0", r.returncode == 0, r.stderr)
        brows = {row["date"]: row for row in read_scores_csv(b_scores)}

        d26 = (START + timedelta(days=26)).isoformat()
        d27 = (START + timedelta(days=27)).isoformat()
        d37 = (START + timedelta(days=37)).isoformat()
        d39 = (START + timedelta(days=39)).isoformat()

        # day 26: trailing window = days 0..26 = 27 valid days < MIN_HISTORY(28) -> score blank
        check("day26: below MIN_HISTORY -> score blank", brows[d26]["score"] == "", brows[d26])
        check("day26: burden still reported despite blank score",
              brows[d26]["burden"] != "", brows[d26])

        # day 27: window = days 0..27 = 28 valid days, first day to clear MIN_HISTORY.
        # value 6.75 is the max of that window (0..27 strictly increasing) -> less=27, equal=1, n=28
        # score = (27 + 0.5*1) / 28 * 100 = 27.5/28*100 = 98.214... -> round = 98
        check("day27: first day with a score (min-history boundary)",
              brows[d27]["score"] == "98", brows[d27])

        # day 37: window = days 0..37 = 38 valid days. Days 38/39 are AFTER day37 so they are
        # NOT in its trailing window — only day37 itself sits at the tie value within this window.
        # less=37 (days 0..36), equal=1 (itself) -> score = 37.5/38*100 = 98.684... -> round = 99
        check("day37: trailing window excludes future ties",
              brows[d37]["score"] == "99", brows[d37])

        # day 39 (latest overall): window = all 40 valid days. 3-way tie at 9.5 (days 37,38,39).
        # less=37 (days 0..36), equal=3 (days 37,38,39) -> score = (37+1.5)/40*100 = 96.25 -> round 96
        check("day39: midrank formula with a 3-way tie",
              brows[d39]["score"] == "96", brows[d39])

        # ---------- Scenario C: clamping ----------
        c_csv = f"{root}/c/guava.csv"
        c_out = f"{root}/c/page.md"
        c_scores = f"{root}/c/scores.csv"
        write_csv(c_csv, [
            sym_row("2026-02-01", "Weird", 15),    # clamp to 10
            sym_row("2026-02-01", "Weird2", -2),   # clamp to 0
            sym_row("2026-02-01", "Filler", 1),
            sym_row("2026-02-01", "Filler2", 1),
            sym_row("2026-02-01", "Filler3", 1),
            energy_row("2026-02-01", 7),  # clamp to 5
            mood_row("2026-02-01", 0),    # clamp to 1
        ])
        w(c_out, page_text())
        r = run(root, c_csv, c_out, c_scores, True)
        check("scenario C: apply exits 0", r.returncode == 0, r.stderr)
        check("clamp warning printed for out-of-range values",
              "warn:" in r.stdout and "clamped" in r.stdout, r.stdout)
        crow = read_scores_csv(c_scores)[0]
        # burden = 10^2/10 (clamped Weird) + 0^2/10 (clamped Weird2) + 3*(1^2/10) = 10+0+0.3 = 10.3
        check("value 15 clamped to 10 (reflected in burden)", crow["burden"] == "10.3", crow)
        check("energy clamped to 5", crow["energy"] == "5", crow)
        check("mood clamped to 1", crow["mood"] == "1", crow)

        # ---------- Scenario D: quoted multi-line CSV fields must not corrupt parsing ----------
        d_csv = f"{root}/d/guava.csv"
        d_out = f"{root}/d/page.md"
        d_scores = f"{root}/d/scores.csv"
        tricky_notes = "line one\nline two, with a comma embedded"
        d_rows = [sym_row("2026-03-01", "WithNote", 6, notes=tricky_notes)]
        for j in range(1, 5):
            d_rows.append(sym_row("2026-03-01", "Filler%d" % j, 0))
        d_rows.append(sym_row("2026-03-02", "AfterNote", 7))
        for j in range(1, 5):
            d_rows.append(sym_row("2026-03-02", "Filler%d" % j, 0))
        write_csv(d_csv, d_rows)
        w(d_out, page_text())
        r = run(root, d_csv, d_out, d_scores, True)
        check("scenario D: apply exits 0", r.returncode == 0, r.stderr)
        drows = {row["date"]: row for row in read_scores_csv(d_scores)}
        check("scenario D: exactly 2 dates parsed (embedded newline/comma didn't split/merge rows)",
              len(drows) == 2, drows)
        check("day after quoted-notes row parses cleanly (burden 4.9)",
              drows["2026-03-02"]["burden"] == "4.9", drows)
        check("quoted-notes day itself parses cleanly (burden 3.6)",
              drows["2026-03-01"]["burden"] == "3.6", drows)

        # ---------- Scenario F (contract item 10): exact scores-CSV header ----------
        with open(a_scores, encoding="utf-8") as f:
            header_line = f.readline().rstrip("\n")
        check("scores CSV header exact",
              header_line == "date,burden,score,n_symptoms,n_entries,energy,mood,top_drivers,flags",
              header_line)

        # ---------- Scenario G: empty CSV (header only) ----------
        g_csv = f"{root}/g/guava.csv"
        g_out = f"{root}/g/page.md"
        g_scores = f"{root}/g/scores.csv"
        write_csv(g_csv, [])
        original_g_page = page_text()
        w(g_out, original_g_page)
        r = run(root, g_csv, g_out, g_scores, True)
        check("empty CSV: exits 0", r.returncode == 0, r.stderr)
        check("empty CSV: reports no valid days", "no valid days" in r.stdout, r.stdout)
        check("empty CSV: writes nothing (page untouched)",
              open(g_out, encoding="utf-8").read() == original_g_page)
        check("empty CSV: no scores CSV written", not os.path.exists(g_scores))

        # ---------- Scenario E: dry-run, sentinel discipline, idempotency, date bump ----------
        e_csv = f"{root}/e/guava.csv"
        e_out = f"{root}/e/page.md"
        e_scores = f"{root}/e/scores.csv"
        write_csv(e_csv, [
            sym_row("2026-05-01", "Target", 3),
            sym_row("2026-05-01", "Filler1", 1),
            sym_row("2026-05-01", "Filler2", 1),
            sym_row("2026-05-01", "Filler3", 1),
            sym_row("2026-05-01", "Filler4", 1),
        ])
        original_e_page = page_text(dlu="2020-01-01")
        w(e_out, original_e_page)

        # dry-run: no files written/modified
        r = run(root, e_csv, e_out, e_scores, False)
        check("dry-run: exits 0", r.returncode == 0, r.stderr)
        check("dry-run: page file untouched",
              open(e_out, encoding="utf-8").read() == original_e_page)
        check("dry-run: scores CSV not created", not os.path.exists(e_scores))

        # apply #1
        r = run(root, e_csv, e_out, e_scores, True)
        check("apply: exits 0", r.returncode == 0, r.stderr)
        applied_page = open(e_out, encoding="utf-8").read()
        check("apply: hand-written intro survives byte-identical",
              "HANDWRITTEN-INTRO-MARKER must survive edits untouched." in applied_page)
        check("apply: hand-written middle survives byte-identical",
              "HANDWRITTEN-MIDDLE-MARKER must also survive." in applied_page)
        check("apply: hand-written tail survives byte-identical",
              "HANDWRITTEN-TAIL-MARKER final text." in applied_page)
        check("apply: summary sentinel content changed",
              "Latest daily symptom score" in applied_page)
        check("apply: data sentinel content changed",
              "Daily scores — last 35 days" in applied_page)
        check("apply: placeholder summary content gone",
              "placeholder-summary-content" not in applied_page)
        check("apply: placeholder data content gone",
              "placeholder-data-content" not in applied_page)
        check("apply: date_last_updated bumped to latest data date",
              "date_last_updated: 2026-05-01" in applied_page)
        check("apply: old date_last_updated gone",
              "date_last_updated: 2020-01-01" not in applied_page)
        check("apply: scores CSV written", os.path.exists(e_scores))

        # idempotency: second --apply run changes nothing
        mtime_page_1 = os.path.getmtime(e_out)
        mtime_scores_1 = os.path.getmtime(e_scores)
        content_page_1 = open(e_out, encoding="utf-8").read()
        content_scores_1 = open(e_scores, encoding="utf-8").read()
        r2 = run(root, e_csv, e_out, e_scores, True)
        check("apply #2: reports changed: 0", "changed: 0" in r2.stdout, r2.stdout)
        check("apply #2: page content unchanged",
              open(e_out, encoding="utf-8").read() == content_page_1)
        check("apply #2: scores CSV content unchanged",
              open(e_scores, encoding="utf-8").read() == content_scores_1)
        check("apply #2: page mtime unchanged", os.path.getmtime(e_out) == mtime_page_1)
        check("apply #2: scores CSV mtime unchanged",
              os.path.getmtime(e_scores) == mtime_scores_1)

        # missing sentinels -> nonzero exit + ERROR, regardless of --apply
        e2_out = f"{root}/e/page-missing-sentinels.md"
        w(e2_out, page_text(include_data_sentinels=False))
        r3 = run(root, e_csv, e2_out, f"{root}/e/scores-missing.csv", False)
        check("missing sentinels: nonzero exit", r3.returncode != 0, r3.returncode)
        check("missing sentinels: ERROR reported",
              "ERROR" in r3.stdout or "ERROR" in r3.stderr, (r3.stdout, r3.stderr))
    finally:
        shutil.rmtree(root)
    print()
    if fails:
        print(f"{len(fails)} FAILED: {fails}")
        sys.exit(1)
    print("ALL TESTS PASSED")


if __name__ == "__main__":
    main()
